project:
  type: book
  output-dir: docs

book:
  title: "Outil de suivi de collecte MASA"
  author: "Anaël Delorme"
  date: "23/10/2023"
  search: true
  repo-url: https://github.com/anaelDelorme/doc_outil_suivi_collecte
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - prerequis.qmd
    - donnees.qmd
    - dev_app_shiny.qmd
    - squellete_appli.qmd
    - add_box.qmd
    - add_shinymanager.qmd
    - deploy.qmd
    - modify.qmd
    - debug.qmd
    - references.qmd
  output-file: "outil_suivi_collecte_masa"
  
bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

editor: source

